version: "2.4"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    #volumes:
    # - ./frontend:/app
    networks:
      - app-network
    depends_on:
      - backend
    

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=main.py
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app_db
    networks:
      - app-network
    depends_on:
      - db
    command: flask run --host=0.0.0.0 --port=5000

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  app-network:
